### PR TITLE
Fix xeus cpp build

### PR DESCRIPTION
**Pull request by mcbarton**
# Description

Please include a summary of changes, motivation and context for this PR.

This changes the ci which builds the emscripten version of xeus-cpp to match the PR in https://github.com/compiler-research/xeus-cpp/pull/199/files

Fixes # (issue)

## Type of change

Please tick all options which are relevant.

- [x] Bug fix
- [ ] New feature
- [ ] Requires documentation updates

## Testing

Please describe the test(s) that you added and ran to verify your changes.

## Checklist

- [x] I have read the contribution guide recently

### CODE REVIEW

**Comment by anutosh491** [comment]
Thanks for the PR, once done I shall try reviewing it.

**Comment by anutosh491** [comment]
Curious about few things
i) Did we rebuild the cache to use llvm 19.1.6 
ii) If yes, maybe consider going through this comment of mine (https://github.com/compiler-research/xeus-cpp/pull/199#issuecomment-2558341781)

The above would allow simple stuff (like hello world etc) to run absolutely as we expect it to but problems would arise when we are interested in anything to do with files or using Jupyter Lite's file system for accessing anything. For eg 
```
#include <iostream>
#include <fstream>

std::ofstream outfile ("userfile.txt");

outfile << "custom user file!" << std::endl;

outfile.close();
```

**Comment by mcbarton** [comment]
@anutosh491 I'm just about the rebuild the cache with this patch https://github.com/emscripten-forge/recipes/blob/main/recipes/recipes_emscripten/llvm/patches/shift_temporary_files_to_tmp_dir.patch

**Comment by anutosh491** [comment]
Thank you. Another thing which maybe you could here, is to just improve the emscripten build instructions accordingly !

**Comment by mcbarton** [comment]
@anutosh491 Wi

> Thank you. Another thing which maybe you could do here, is to just improve the emscripten build instructions accordingly ?

@anutosh491 I will do this tomorrow morning.

**Comment by anutosh491** [comment]
Absolutely fine ;)

**Review by anutosh491 — APPROVED** [review]
Looks good !

**Comment by anutosh491** [comment]
That being said, merging this before the xeus-cpp PR doesn't make sense correct ?
We also want the changes that are present on the xeus-cpp PR which would be fetched from HEAD while building xeus-cpp-lite through cppinterop's CI

**Comment by anutosh491** [comment]
cc @mcbarton

**Pull request merged**
