### PR TITLE
Fix warning micromamba envirnoment setup ci

### PR DESCRIPTION
**Pull request by mcbarton**
This PR is part of the node 16 to node 20 transition. It should stop the warning appearing when the ci runs due to the provision-with-micromamba action.

### CODE REVIEW

**Comment by mcbarton** [comment]
@vgvassilev can this PR be merged? It is part of the node 16 to node 20 transition. After this is merged only the Windows errors will need to be dealth with when the ci runs to have no errors or warnings.

**Comment by maximusron** [comment]
this looks good, but the codecov has dropped very drastically.. we should investigate this...

I tried looking into codecov reports with miromamba and couldn't find much. however. I did notice that both this and the other [PR](https://github.com/compiler-research/CppInterOp/pull/283) have dropped the codecoverage by the same number, see https://app.codecov.io/gh/compiler-research/CppInterOp/pulls

**Comment by mcbarton** [comment]
> this looks good, but the codecov has dropped very drastically.. we should investigate this...
> 
> I tried looking into codecov reports with miromamba and couldn't find much. however. I did notice that both this and the other [PR](https://github.com/compiler-research/CppInterOp/pull/283) have dropped the codecoverage by the same number, see https://app.codecov.io/gh/compiler-research/CppInterOp/pulls

@maximusron The drop in codecov drop has nothing to do with this PR. It dropped when we stopped having coverage turned to true in all Ubuntu jobs. The coverage number on the main branch is not updating from the 88%, after that PR merge seems to be the issue.

**Comment by mcbarton** [comment]
@vgvassilev The issue with the coverage number not updating on the main is due to the token issue just like in xeus-cpp. Can you fix it like you did xeus-cpp repo?
Error message can be seen on the nightly runs of the ci on main.
Error: Codecov token not found. Please provide Codecov token with -t flag.

**Comment by mcbarton** [comment]
@maximusron can you merge this now that I have outlined the issue with the coverage in an issue? It has nothing to do with this PR, but a new condition on coverage report uploading and tokens.

**Review by maximusron — APPROVED** [review]

**Comment by maximusron** [comment]
Node.js 16 actions

**Pull request merged**
