### PR TITLE
Documentation changes as REPL is set to ON by default

### PR DESCRIPTION
**Pull request by faze-geek**
# Description

Continuation of #360 

## Type of change

Please tick all options which are relevant.

- [ ] Bug fix
- [ ] New feature
- [x] Requires documentation updates

## Checklist

- [x] I have read the contribution guide recently

### CODE REVIEW

**Comment by anutosh491** [comment]
there's some uncertainty here, do we need to have use_cling=off everywhere ?

As in if we say repl is on by default, I am guessing that also implies cling is off by default ?

**Comment by faze-geek** [comment]
Yes that was mentioned in this [comment](https://github.com/compiler-research/CppInterOp/pull/360#discussion_r1886413956) as well, we can go ahead and remove all `DUSE_CLING=off `instances.

**Comment by vgvassilev** [comment]
> there's some uncertainty here, do we need to have use_cling=off everywhere ?
> 
> As in if we say repl is on by default, I am guessing that also implies cling is off by default ? (Is this what we were trying to achieve @vgvassilev ?)

Yes

**Comment by vgvassilev** [comment]
> Yes that was mentioned in this [comment](https://github.com/compiler-research/CppInterOp/pull/360#discussion_r1886413956) as well, we can go ahead and remove all `DUSE_CLING=off `instances.

Yes. We should do that.

**Comment by mcbarton** [comment]
@faze-geek let me know when you've removed all references to use_cling=off and i'll review.

**Comment by faze-geek** [comment]
@mcbarton You can have a look right now.

**Review by anutosh491 — APPROVED** [review]
I think this looks fine to me !

**Comment by mcbarton** [comment]
@faze-geek You need to make changes in the recently introduced emscripten build instructions file.

**Comment by faze-geek** [comment]
> @faze-geek You need to make changes in the recently introduced emscripten build instructions file. 

Will make those changes quick. Thanks !

**Pull request merged**
